# ~/.config/hypr/hyprlock.conf

background {
    monitor =
    path = screenshot

    blur_passes = 4
    blur_size = 10
}

label {
    monitor =

    text = cmd[update:1000] echo "$(date '+%H:%M')"

    font_family = CaskaydiaCove Nerd Font
    font_size = 180

    position = 0, 250
    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] echo "$(date '+%A, %d %B %Y')"

    font_family = CaskaydiaCove Nerd Font
    font_size = 40

    position = 0, 120
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 500, 80

    outline_thickness = 3

    outer_color = rgb(89b4fa)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)

    rounding = 12

    fade_on_empty = false
    placeholder_text = Password...

    dots_size = 0.3
    dots_spacing = 0.3

    position = 0, -40
    halign = center
    valign = center
}
