general {
    lock_cmd = pidof hyprlock || hyprlock       # Prevents multiple lock screens
    before_sleep_cmd = loginctl lock-session    # Locks the screen before the system sleeps
    after_sleep_cmd = hyprctl dispatch dpms on  # Turns the display back on after sleep
}

# Dims the screen backlight after 2.5 minutes
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Locks the screen after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turns off the display after 5.5 minutes
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspends the system after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
